image: node:carbon-alpine

stages:
  - build
  - lint
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install -g @quasar/cli
    - quasar build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

eslint:
  stage: lint
  script:
    - npm install --progress=false
    - npm run lint

registry-deploy:
  image: docker:17.04-git
  services:
    - docker:17.04-dind
  stage: deploy
  variables:
    DASHBOARD_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $DASHBOARD_RELEASE_IMAGE .
    - docker tag $DASHBOARD_RELEASE_IMAGE "$CI_REGISTRY_IMAGE:stable"
    - docker push "$CI_REGISTRY_IMAGE:stable"
  only:
    - master
  environment: production
  tags:
    - docker