stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm run build --if-present
- name: Lint
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm run lint
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dashboard:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
  when:
    branch:
      include:
      - master
notification: {}