version: '3'
services:
  front.service:
    container_name: hockey-dashboard
    build: ./
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8082:8082"
    tty: true
    stdin_open: true