apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: air-rockey-dashboard
  annotations:  
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - rockey-dashboard.lappis.rocks
    secretName: letsencrypt-prod
  rules:
  - host: rockey-dashboard.lappis.rocks
    http:
      paths:
      - backend:
          serviceName: dashboard-service
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: dashboard-service
  namespace: air-rockey-dashboard
spec:
  selector:
    app: dashboard
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: air-rockey-dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: dashboard
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8082